conferenceapp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register, name='register'),
    path('accounts/profile/',user_views.profile, name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users\login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
     path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', include('event.urls')),

]

event/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from rest_framework import routers
from .views import (PostDetailView, AddDislike, AddLike)
router=routers.DefaultRouter()
router.register('events', views.PostViewSet)

urlpatterns = [
    path("", views.index, name="index"),
    path("events/mine", views.events_list_mine, name="events_list_mine"),
    path("search_events", views.search_events, name="search-events"),
    path("events/future", views.events_list_future, name="events_list_future"),
    path("events/past", views.events_list_past, name="events_list_past"),
    path("events/all", views.events_list_all, name="events_list_all"),
    path("events/archive", views.events_list_archived, name="events_list_archived"),
    path("event/create", views.event_create, name="event_create"),
    path("event/<int:event_id>/update", views.event_update, name="event_update"),
    path('event/<int:pk>/', PostDetailView.as_view( template_name='conference\event_detail.html'), name='event-detail'),
    path('event/<int:pk>/like', AddLike.as_view(), name='like'),
    path('event/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
    path(
        "event/<int:event_id>/update_categories",
        views.event_update_categories,
        name="event_update_categories",
    ),
    path(
        "event/<int:event_id>/update_sessions",
        views.event_update_sessions,
        name="event_update_sessions",
    ),
    path("event/<int:event_id>/manage", views.event_manage, name="event_manage"),
    path(
        "event/<int:event_id>/options_summary",
        views.event_download_options_summary,
        name="event_download_options_summary",
    ),
    path(
        "event/<int:event_id>/participants_list",
        views.event_download_participants_list,
        name="event_download_participants_list",
    ),
    path("choice/create/<int:event_id>", views.choice_create, name="choice_create"),
    path("choice/<int:choice_id>/update", views.choice_update, name="choice_update"),
    path("choice/<int:choice_id>/delete", views.choice_delete, name="choice_delete"),
    path("booking/create/<int:event_id>", views.booking_create, name="booking_create"),
    path(
        "booking/create_on_behalf/<int:event_id>",
        views.booking_create_on_behalf,
        name="booking_create_on_behalf",
    ),
    path(
        "booking/<int:booking_id>/update", views.booking_update, name="booking_update"
    ),
    path(
        "booking/<int:booking_id>/session",
        views.booking_session_update,
        name="booking_session_update",
    ),
    path(
        "booking/<int:booking_id>/cancel", views.booking_cancel, name="booking_cancel"
    ),
    path(
        "booking/<int:booking_id>/payment/confirm",
        views.booking_payment_confirm,
        name="booking_payment_confirm",
    ),
    path(
        "booking/<int:booking_id>/payment/cancel",
        views.booking_payment_confirm,
        name="booking_payment_cancel",
        kwargs={"cancel": True},
    ),
    path(
        "booking/<int:booking_id>/payment/exempt",
        views.booking_payment_exempt,
        name="booking_payment_exempt",
    ),
    path(
        "booking/<int:booking_id>/payment/unexempt",
        views.booking_payment_exempt,
        name="booking_payment_unexempt",
        kwargs={"cancel": True},
    ),
    path(
        "booking/<int:booking_id>/send_invite",
        views.booking_send_invite,
        name="booking_send_invite",
    ),
    path("accounts/delete", views.user_delete, name="user_delete"),
]

event/models.py
from decimal import Decimal

from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils import timezone as django_timezone
from django.core.mail.message import EmailMultiAlternatives
from django.db.models.aggregates import Count
from .tz_utils import add_to_zones_map
from timezone_field import TimeZoneField
from django.contrib.auth.models import User
import icalendar
from icalendar.prop import vCalAddress, vText
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
import logging


# A default datetime format (too lazy to use the one in settings)
dt_format = "%a, %d %b %Y %H:%M"


def end_of_day(when, timezone):
    """
    Returns the end of the day after of the given datetime object
    @param when: the datetime to use
    @param timezone: the timezone in which to calculate the end of the day
    """
    local_dt = when.astimezone(timezone)
    return timezone.normalize(local_dt.replace(hour=23, minute=59, second=59))


class Event(models.Model):
    """
    An event being organised
    """

    PUB_STATUS_CHOICES = (
        ("PUB", "Public"),
        ("REST", "Restricted"),
        ("PRIV", "Private"),
        ("UNPUB", "Unpublished"),
        ("ARCH", "Archived"),
    )

    title = models.CharField(max_length=64, unique=True)
    start = models.DateTimeField(help_text="Local start date and time")
    end = models.DateTimeField(
        blank=True, null=True, help_text="Local end date and time"
    )
    timezone = TimeZoneField(
        default="Europe/London", help_text="Local timezone of your event"
    )

    description = models.TextField(blank=True)
    likes = models.ManyToManyField(User, blank=True, related_name='likes')
    dislikes = models.ManyToManyField(User, blank=True, related_name='dislikes')
    pub_status = models.CharField(
        max_length=8,
        choices=PUB_STATUS_CHOICES,
        default="UNPUB",
        verbose_name="Publication status",
        help_text=(
            "Public: Visible and bookable by all; "
            "Restricted: Visible and Bookable by invited groups; "
            "Private: Visible by participant, bookable by all; "
            "Unpublished: Visible by organisers, not bookable; "
            "Archived: Not visible, not bookable"
        ),
    )

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="events_owned",
        on_delete=models.CASCADE,
        help_text="Main organiser",
    )
    organisers = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name="events_organised"
    )

    booking_close = models.DateTimeField(
        blank=True, null=True, help_text="Limit date and time for registering"
    )
    choices_close = models.DateTimeField(
        blank=True, null=True, help_text="Limit date and time for changing choices"
    )

    max_participant = models.PositiveSmallIntegerField(
        default=0,
        help_text="Maximum number of participants to this event (0 = no limit)",
    )


    def __unicode__(self):
        result = "{0} - {1:%x %H:%M}".format(self.title, self.start)
        if self.end is not None:
            result += " to {0:%x %H:%M}".format(self.end)
        return result

    def __init__(self, *args, **kwargs):
        """
        Constructor to initialise some instance-level variables
        """
        super(Event, self).__init__(*args, **kwargs)
        # Cache dictionnary to save DB queries
        self.users_values_cache = None

    def clean(self):
        """
        Validate this model
        """
        super(Event, self).clean()
        if self.booking_close and self.booking_close > self.start:
            raise ValidationError("Bookings must close before the event starts")
        if self.choices_close and self.choices_close > self.start:
            raise ValidationError("Choices must close before the event starts")
        if (
            self.booking_close
            and self.choices_close
            and self.booking_close > self.choices_close
        ):
            raise ValidationError("Bookings must close before choices")

    def _populate_users_cache(self):
        """
        Fill in the cache of info about users related to this event
        """
        if self.users_values_cache is not None:
            return

        self.users_values_cache = {}

        def add_cache(user, category):
            user_cache = self.users_values_cache.get(user, {})
            user_cache[category] = True
            self.users_values_cache[user] = user_cache

        for orga in self.organisers.all():
            add_cache(orga.id, "__orga_group_")

        users = get_user_model().objects.all().prefetch_related("groups")
        for cat in self.categories.all():
            for user_id in [u.id for u in users if cat.match(u.groups.all())]:
                add_cache(user_id, cat.name)

    def _get_from_users_cache(self, user_id, key, default=None):
        """
        @return: the value for a user_id/key pair from the cache.
        @param default: default value if user/key is not found
        """
        self._populate_users_cache()
        return self.users_values_cache.get(user_id, {}).get(key, default)

    def user_is_organiser(self, user):
        """
        Check if the given user is part of the organisers of the event
        """
        is_orga = self._get_from_users_cache(user.id, "__orga_group_", False)
        is_owner = user == self.owner
        return is_orga or is_owner

    def get_user_category(self, user):
        """
        Finds the Event's category for the given user.
        @returns the Category object or None if none matches
        """
        if not self.categories:
            return None

        for category in self.categories.all():
            if self._get_from_users_cache(user.id, category.name, False):
                return category
        logging.warning("User {0} is in no category for {1}".format(user, self))
        return None

    def user_price(self, user):
        """
        Gets the price for a given user based on his category
        """
        cat = self.get_user_category(user)
        if cat is not None:
            return cat.price
        else:
            return None

    def user_can_update(self, user):
        """
        Check that the given user can update the event
        """
        return user.is_superuser or self.user_is_organiser(user)

    def user_can_list(self, user, list_archived):
        """
        Check that the given user can view the event in the list
        @param user: The user signed in. If not specified, assume anonymous user
        @param list_archived: Boolean to indicated it archived events are visible
        """
        if self.pub_status == "PUB":
            return True
        elif user.is_anonymous:
            # All other statuses are invisible to anonymous
            return False
        elif self.pub_status == "REST":
            return (
                user.is_superuser
                or self.user_is_organiser(user)
                or self.get_user_category(user) is not None
            )
        elif self.pub_status == "PRIV" or self.pub_status == "UNPUB":
            user_has_booking = (
                self.bookings.filter(person=user, cancelledOn=None).count() > 0
            )
            return user.is_superuser or user_has_booking or self.user_is_organiser(user)
        elif self.pub_status == "ARCH":
            if list_archived:
                return user.is_superuser or self.user_is_organiser(user)
            else:
                return False
        else:
            raise Exception("Unknown publication status: {0}".format(self.pub_status))

    def user_can_book(self, user):
        """
        Check if the given user can book the event
        """
        if user.is_anonymous:
            # All statuses are non-bookable by anonymous
            return False

        if self.pub_status == "PUB":
            return True
        elif self.pub_status == "REST":
            return (
                self.user_is_organiser(user) or self.get_user_category(user) is not None
            )
        elif self.pub_status == "PRIV":
            return True
        elif self.pub_status == "UNPUB":
            return False
        elif self.pub_status == "ARCH":
            return False
        else:
            raise Exception("Unknown publication status: {0}".format(self.pub_status))

    def get_real_end(self):
        """
        Get the real datetime of the end of the event
        """
        if self.end is not None:
            return self.end
        else:
            return end_of_day(self.start, self.timezone)

    def is_ended(self):
        """
        Check if the event is ended
        """
        return self.get_real_end() < django_timezone.now()

    def is_booking_open(self):
        """
        Check if the event is still open for bookings
        """
        closed = (
            self.booking_close is not None
            and django_timezone.now() > self.booking_close
        )
        published = self.pub_status in ("PUB", "REST", "PRIV")
        return (
            self.is_choices_open() and not self.is_ended() and not closed and published
        )

    def is_choices_open(self):
        """
        Check if the event is still open for choices
        """
        closed = (
            self.choices_close is not None
            and django_timezone.now() > self.choices_close
        )
        published = self.pub_status in ("PUB", "REST", "PRIV")
        return not self.is_ended() and not closed and published

    def is_fully_booked(self):
        """
        Checks if it is still possible to add a booking regarding the maximum number
        of participants
        """
        return 0 < self.max_participant <= self.get_active_bookings().count()

event/templates/conference/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static "OneEvent/OneEvent.css" %}" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!--[if lt IE 7]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation"
        {% if navbar_color %}style="background-color:{{ navbar_color }}"{% endif %}>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar-menu-entries">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
        
            </div>
            <div class="collapse navbar-collapse" id="navbar-menu-entries">
                <ul class="nav navbar-nav">
                    <li>
                        <ol class="breadcrumb">
                            <li>
                                <a href="{% url 'events_list_all' %}">
                                    <span class="glyphicon glyphicon-home"></span>
                                    <span>Home</span>
                                </a>
                            </li>
                            {%  block navbar_breadcrumbs %}{% endblock %}
                        </ol>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% include 'conference/navbar_auth.html' %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

        <div id="messages-row" class="row">
            <!-- This is the template message that is cloned to create new messages from JS. -->
            <div class="alert alert-dismissible hidden" id="alert-template">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
            </div>
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
                <span>{{message}}</span>
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
            </div>
            {% endfor %}
        {% endif %}
        </div>

        <div id="main-row" class="row">
            <div class="container-fluid">
            {% block page_heading %}
                <div class="row text-center bottom-separation"><h1>
                    <span class="label label-primary">{% block heading_action %}{% endblock %}</span>
                    {% block heading_title %}{% endblock %}
                </h1></div>
            {% endblock %}

            {% block content %}{% endblock %}
            </div>
        </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Include custom JS -->
    <script src="{% static 'OneEvent/OneEvent.js' %}"></script>
</body>
</html>

event/templates/conference/base_confirmation.html
{% extends "conference/base.html" %}

{% block content %}
<div class="row text-center">
    <form action="{% block post_url %}{% endblock %}" method="post">
    {% csrf_token %}
    {% block additional_info %}{% endblock %}
    <input class="btn btn-default" type="submit" value="Confirm" />
    </form>
</div>
<div class="row" style="margin-top: 10px">
    {% block extra_details %}{% endblock %}
</div>
{% endblock %}

event/templates/conference/booking_cancel.html
{% extends "conference/base_confirmation.html" %}

{% block navbar_breadcrumbs %}
    <li class="active">Unregister</li>
{% endblock %}

{% block heading_action %}Unregister{% endblock %}
{% block heading_title %}{{ booking.event.title }}
    <small>{{ booking.event.start|date:"D, d N Y H:i" }}</small>
{% endblock %}

{% block post_url %}{% url 'booking_cancel' booking_id=booking.id %}{% endblock %}

event/templates/conference/booking_create_on_behalf.html
{% extends "conference/base.html" %}
{% load crispy_forms_tags %}

{% block navbar_breadcrumbs %}
    <li class="active">Create Booking</li>
{% endblock %}

{% block heading_action %}Create Booking{% endblock %}
{% block heading_title %}{{ event.title }}
    <small>{{ event.start|date:"D, d N Y H:i" }}</small>
{% endblock %}

{% block content %}
    {% crispy form %}
{% endblock %}

event/templates/conference/booking_payment_confirm.html
{% extends "conference/base_confirmation.html" %}

{% block navbar_breadcrumbs %}
    <li class="active">Confirm Payment</li>
{% endblock %}

{% block heading_action %}
    {% if cancel %}Refund{% else %}Confirm Payment{% endif %}
{% endblock %}
{% block heading_title %}{{ booking.person.get_full_name }}
<small>for</small> {{ booking.event.title }}{% endblock %}

{% block post_url %}
    {% if cancel %}
        {% url 'booking_payment_cancel' booking_id=booking.id %}
    {% else %}
        {% url 'booking_payment_confirm' booking_id=booking.id %}
    {% endif %}
{% endblock %}

event/templates/conference/choice_delete.html
{% extends "conference/base_confirmation.html" %}

{% block navbar_breadcrumbs %}
    <li class="active">Delete Choice</li>
{% endblock %}

{% block heading_action %}Delete Choice{% endblock %}
{% block heading_title %}{{ choice.title }}
    <small>{{ choice.event.title }}</small>
{% endblock %}

{% block additional_info %}
<h2 class="text-danger">You will loose choices made by all participants !</h2>
{% endblock %}

{% block post_url %}{% url 'choice_delete' choice_id=choice.id %}{% endblock %}

event/templates/conference/events_list.html
{% extends "conference/base.html" %}
{% load tz %}

{% block heading_action %}Follow Conferences{% endblock %}
{% block heading_title %}{% endblock %}
 {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% block navbar_breadcrumbs %}
    <li class="dropdown active">
        <a href="#" class="dropdown-toggle"
            data-toggle="dropdown" title="Conferences">
            <span class="">
                {% if events_shown == 'fut' %}
                    Coming Up
                {% elif events_shown == 'past' %}
                    Past Conferences
                {% elif events_shown == 'all' %}
                    Conferences
                {% elif events_shown == 'mine' %}
                    My Conferences
                {% elif events_shown == 'arch' %}
                    Archived Conferences
                {% endif %}
            </span>
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'events_list_mine' %}">My conferences</a></li>
            <li><a href="{% url 'events_list_all' %}">All conferences</a></li>
            <li><a href="{% url 'events_list_future' %}">Coming up</a></li>
            <li><a href="{% url 'events_list_past' %}">Past conferences</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'events_list_archived' %}">Archived conferences</a></li>
            <li class="divider"></li>
        </ul>
    </li>
    <a href="{% url 'event_create' %}">
        <span class="glyphicon glyphicon-plus"></span>
        New conference
    
    </a>
    <li>
         <div>
        <form class="d-flex" method=POST action="{% url 'search-events' %}">
            {% csrf_token %}
            <input type="text" name="searched" placeholder="Search">
          </form> 
    </div> </li>


{% endblock %}

{% block content %}

<div class="row"><div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Conference</th>
                <th>Date (local)</th>
                <th>Infos</th>
                <th>Options</th>
                {% if user.is_authenticated %}
                <th><!--  Actions --></th>
                {%endif%}
            </tr>
        </thead>
        <tbody>
            {% for event_info in events %}
            {% timezone event_info.event.timezone %}
            <tr>
                <td>
                    <p>
                        <h4><a class="article-title" href="{% url 'event-detail' event_info.event.id %}">{{ event_info.event.title }}</a></h4>
                        {{ event_info.event.title }}
                        <span class="badge pull-right">{{ event_info.event.timezone }}</span>
                    </p>
                    {% if event_info.event.location_name %}<p><small>at </small>{{event_info.event.location_name}}</p>{% endif %}
                </td>
                <td><p>{{ event_info.event.start|date:"D, d N Y H:i" }}</p>
                    {% if event_info.event.end %}<p>- {{ event_info.event.end|date:"D, d N Y H:i" }}</p>{% endif %}
                    <p></p>
                </td>
                <td>
                    {% if event_info.event.max_participant > 0 %}
                    <p>Participants: {{event_info.event.get_active_bookings.count}}/{{event_info.event.max_participant}}</p>
                    {% endif %}
                    {% if event_info.event.booking_close %}
                    <p>Registration closes: {{event_info.event.booking_close|date:"D, d N Y H:i"}}</p>
                    {% endif %}
        
                </td>
       
                {% if user.is_authenticated %}
                <td>
                <div>
                {% if event_info.booking %}
                    {% if event_info.event.is_choices_open %}
                    
                    <a href="{% url 'booking_update' booking_id=event_info.booking.id %}" class="btn btn-success">
                        {% if event_info.event.choices.count > 0  %}
                        Choices
                        {% else %}
                        Update
                        {% endif %}
                    </a>
                    {% else %}
                    <button type="button" class="btn btn-success disabled enable-tooltip"
                        data-toggle="tooltip" data-placement="top" title="Sorry you missed out">Choices Closed</button>
                    {% endif %}
                    {% if event_info.user_can_cancel %}
                    <a href="{% url 'booking_cancel' booking_id=event_info.booking.id %}" class="btn btn-danger">Unregister</a>
                    {% else %}
                    <button type="button" class="btn btn-danger disabled enable-tooltip"
                        data-toggle="tooltip" data-placement="top" title="Sorry you missed out">Event Closed</button>
                    {% endif %}
                {% elif event_info.user_can_book %}
                    {% if event_info.event.is_booking_open %}
                        {% if event_info.event.is_fully_booked %}
                        <button type="button" class="btn btn-info disabled enable-tooltip"
                            data-toggle="tooltip" data-placement="top" title="Sorry you missed out">Event Full</button>
                        {% else %}
                        <a href="{% url 'booking_create' event_id=event_info.event.id %}" class="btn btn-info">Register</a>
                        {% endif %}
                    {% else %}
                        <button type="button" class="btn btn-info disabled enable-tooltip"
                            data-toggle="tooltip" data-placement="top" title="Sorry you missed out">Event Closed</button>
                    {% endif %}
                {% endif %}
                </div>

                {% if event_info.user_can_update %}
                <div>
                    <a href="{% url 'event_manage' event_id=event_info.event.id %}"
                       class="btn btn-sm btn-primary">Manage</a>
                    <a href="{% url 'event_update' event_id=event_info.event.id %}"
                       class="btn btn-sm btn-warning">Edit</a>
                    ({{event_info.event.get_pub_status_display }})
                </div>
                {% endif %}
                </td>
                {% endif %}
            </tr>
            {% endtimezone %}
            {% endfor %}
        </tbody>
    </table>
</div></div>

{% endblock %}

event/templates/conference/navbar_auth_avatar.html
<span class="">{{ user.get_full_name|default:user.email|default:user.username }}</span>

event/templates/conference/user_delete.html
{% extends "conference/base_confirmation.html" %}

{% block navbar_breadcrumbs %}
    <li>Account</li>
    <li class="active">Delete</li>
{% endblock %}

{% block heading_action %}Delete User{% endblock %}

{% block heading_title %}{{ user.email }}{% endblock %}

{% block post_url %}{% url 'user_delete' %}{% endblock %}

{% block additional_info %}
    <h2 class="text-danger">Are you sure you want to delete your account?</h2>
    <h3>
        The following records will also be deleted from the application.
        They will not be recoverable!
    </h3>
{% endblock %}

{% block extra_details %}
    {% for event in user.events_owned.all %}
        <div class="panel panel-info collapsible-caret">
            <div class="panel-heading collapsible-toggle"
                 data-toggle="collapse" data-target="#collapseChoices{{ event.id }}">
                <strong>{{ event.title }}</strong>
                <span>{{ event.start|date:"D, d N Y" }}</span>
                <a href="{% url 'event_update' event_id=event.id %}"
                    onclick="avoid_collapse_toggle(event)"
                    class="btn btn-info" style="margin-left: 10px"
                >
                    Edit event
                </a>
            </div>
            <div id="collapseChoices{{ event.id }}" class="panel-collapse collapse in table-responsive" >
                <div class="panel-body">
                    <ul class="list-unstyled">
                        <li>
                            <strong>From</strong> {{ event.start|date:"D, d N Y H:i" }}
                            <strong>to</strong> {{ event.get_real_end|date:"D, d N Y H:i" }}
                            ({{ event.timezone }})
                        </li>
                        <li><strong>Location:</strong> {{ event.location_name }}</li>
                        <li><strong>Status:</strong> {{ event.get_pub_status_display }}</li>
                        <li><strong>Participants:</strong>
                            {{ event.get_active_bookings.count }} confirmed
                            ({{ event.bookings.count }} total}</li>
                    </ul>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}